LineLogin/Pages/Callback.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

namespace LineLogin.Pages
{
    public class CallbackModel : PageModel
    {
        public IConfigurationSection Channel_ID, Channel_Secret, CallbackURL;

        public CallbackModel(IConfiguration config)
        {
            Channel_ID = config.GetSection("LINE-Login-Setting:Channel_ID");
            Channel_Secret = config.GetSection("LINE-Login-Setting:Channel_Secret");
            CallbackURL = config.GetSection("LINE-Login-Setting:CallbackURL");
        }

        public IActionResult OnGet()
        {

            //取得返回的code
            var code = HttpContext.Request.Query["code"].ToString();
            if (string.IsNullOrEmpty(code))
            {
                using (var sw = new System.IO.StreamWriter(HttpContext.Response.Body, System.Text.Encoding.UTF8))
                {
                    sw.Write("沒有正確回應code");
                    sw.Flush();
                    return new OkResult();
                }
            }
            //顯示，測試用
            //Response.Write("<br/> code : " + code);
            //從Code取回toke
            var token = isRock.LineLoginV21.Utility.GetTokenFromCode(code,
                Channel_ID.Value,  //TODO:請更正為你自己的 client_id
               Channel_Secret.Value, //TODO:請更正為你自己的 client_secret
                CallbackURL.Value);  //TODO:請檢查此網址必須與你的LINE Login後台Call back URL相同



            //顯示，測試用(正式環境我們不會曝露token)
            //using (var sw = new System.IO.StreamWriter(HttpContext.Response.Body, System.Text.Encoding.UTF8))
            //{
            //    sw.Write("<br/> token : " + token.access_token);
            //    sw.Flush();
            //}

            //利用access_token取得用戶資料
            var user = isRock.LineLoginV21.Utility.GetUserProfile(token.access_token);
            //利用id_token取得Claim資料
            var JwtSecurityToken = new System.IdentityModel.Tokens.Jwt.JwtSecurityToken(token.id_token);
            var email = "";
            //如果有email
            if (JwtSecurityToken.Claims.ToList().Find(c => c.Type == "email") != null)
                email = JwtSecurityToken.Claims.First(c => c.Type == "email").Value;

            //顯示，測試用
            //using (var sw = new System.IO.StreamWriter(HttpContext.Response.Body, System.Text.Encoding.UTF8))
            //{
            //    sw.Write("<br/> user : " + Newtonsoft.Json.JsonConvert.SerializeObject(user));
            //    sw.Write("<br/> emal : " + email);
            //    sw.Flush();
            //}

            #region SignIn
            var claims = new List<Claim>
                {
                    //use email or LINE user ID as login name
                    new Claim(ClaimTypes.Name, string.IsNullOrEmpty( email ) ? user.userId:email ),
                    //use LINE displayName as FullName
                    new Claim("FullName",user.displayName),
                    new Claim(ClaimTypes.Role, "nobody"),
                };

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
            };

            HttpContext.SignInAsync(
               CookieAuthenticationDefaults.AuthenticationScheme,
               new ClaimsPrincipal(claimsIdentity),
               authProperties);
            #endregion

            //導入首頁，帶入token
            //(注意這是範例，token不該用明碼傳遞，也不該出現在用戶端，你應該自行記錄在資料庫或ServerSite session中)
            return Redirect($"index?token={System.Web.HttpUtility.UrlEncode(token.access_token)}&email={email}");
        }
    }
}

LineLogin/Pages/index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using isRock.LineBot.Extensions;

namespace LineLogin.Pages
{
    public class indexModel : PageModel
    {
        public IConfigurationSection Channel_ID, Channel_Secret, CallbackURL;

        [BindProperty]
        public string txb_token { get; set; }
        [BindProperty]
        public string txb_email { get; set; }
        [BindProperty]
        public string txb_area1 { get; set; }
        public indexModel(IConfiguration config)
        {
            Channel_ID = config.GetSection("LINE-Login-Setting:Channel_ID");
            Channel_Secret = config.GetSection("LINE-Login-Setting:Channel_Secret");
            CallbackURL = config.GetSection("LINE-Login-Setting:CallbackURL");
        }

        public void OnGet()
        {
            this.txb_token = HttpContext.Request.Query["token"].ToString();
            this.txb_email = HttpContext.Request.Query["email"].ToString();
        }

        public void OnPostGetUserProfile()
        {
            //利用access_token取得用戶資料
            var user = isRock.LineLoginV21.Utility.GetUserProfile(this.txb_token);
            txb_area1 = user.ToJson();
        }
    }
}

LineLogin/Pages/Callback.cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model LineLogin.Pages.CallbackModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Callback</title>
</head>
<body>
</body>
</html>

LineLogin/Pages/index.cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model LineLogin.Pages.indexModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.js"></script>

    <title>index</title>
    <script>
        //建立OAuth 身分驗證頁面並導入
        function Auth() {
            var URL = 'https://access.line.me/oauth2/v2.1/authorize?';
            URL += 'response_type=code';
            URL += '&client_id=@Model.Channel_ID.Value';   //TODO:這邊要換成你的client_id
            URL += '&redirect_uri=@Model.CallbackURL.Value';   //TODO:要將此redirect url 填回你的 LineLogin後台設定
            URL += '&scope=openid%20profile';
            URL += '&state=abcde';
            window.location.href = URL;
        }
        //建立OAuth 身分驗證頁面並導入
        function AuthWithEmail() {
            var URL = 'https://access.line.me/oauth2/v2.1/authorize?';
            URL += 'response_type=code';
            URL += '&client_id=@Model.Channel_ID.Value';   //TODO:這邊要換成你的client_id
            URL += '&redirect_uri=@Model.CallbackURL.Value';   //TODO:要將此redirect url 填回你的 LineLogin後台設定
            URL += '&scope=openid%20profile%20email';
            URL += '&state=abcde';
            window.location.href = URL;
        }
        //Button1 click
        function Button1_click() {
            Auth();
        }
        //Button2 click
        function Button2_click() {
            AuthWithEmail();
        }
        //hook event
        $(document).ready(function () {
            $('#Button1').click(Button1_click);
            $('#Button2').click(Button2_click);
        });

/**/</script>
</head>
<body>
    <form id="form1" method="post">
        @Html.AntiForgeryToken()
        <div>
            <div class="row" style="margin: 12px">
                <div class="col-lg-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            範例 :  LINE Login  Example
                        </div>
                        <div class="panel-body">
                            使用說明:
                            <ol>
                                <li>
                                    使用此範例Source code，請先更換程式碼中的 'Channel_ID' 與 'Channel_Secret'<br />
                                    (位於appsettings.json)
                                </li>
                                <li>
                                    並且在LINE Developer後台將你申請好的 LINE Login 的callback url 設定好
                                    <br />
                                    (測試階段應為http://localhost:50416/Callback)
                                </li>
                                <li>同時Callback中的client_id與client_secret必須為你申請 LINE Login 後取得的正確資料</li>
                                <li>相關說明請參考 : http://studyhost.blogspot.tw/2016/12/linebot7-line-loginoauth-sso.html </li>
                            </ol>
                            使用步驟:
                            <ol>
                                <li>請點選《使用Line登入》，將會取得該登入用戶的access_token</li>
                                <li>接著按下《取得用戶資訊》，可透過access_token取得用戶資訊</li>
                            </ol>
                            安全性說明:
                            <ol>
                                <li>token會由放在queryString是為了便於您測試和debug, 正式環境不該如此。</li>
                                <li>否則會有嚴重的安全性顧慮</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            測試 LINE Login (current user :   @this.User.Identity.Name )
                        </div>
                        <div class="panel-body">
                            <button class="btn btn-primary pull-left" style="margin-right: 5px" id="Button1" type="button">LINE Login (使用LINE帳號登入)</button>
                            <br />
                            <br />
                            <div>
                                <button class="btn btn-primary" id="Button2" type="button">LINE Login and get OpenID email (使用LINE帳號登入並取得用戶email)</button><br />
                                <label>(透過上面LINE Login按鈕將取得您的email，僅供本範例示範需要使用)</label><br />
                                <label>(申請的LINE Login Channel必須支援OpenID Connect/email) </label>
                            </div>
                            <br />
                            <div class="form-group">
                                <label>取回的token:</label>
                                <input name="txb_token" class="form-control" value="@Model.txb_token" /><br />
                                <label>取回的email: (申請的LINE Login Channel必須支援OpenID Connect/email)</label>
                                <input name="txb_email" class="form-control" value="@Model.txb_email" /><br />
                                <Button type="submit" class="btn btn-primary" asp-page-handler="GetUserProfile" ID="ButtonGetUserProfile">
                                    取得用戶資訊 Get user profile
                                </Button>
                                <br />
                                <textarea runat="server" rows="5" class="form-control" name="textarea1">@Model.txb_area1</textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>
</html>